//This file contains data and prototypes for autoruns. It is autogenerated by StructParser


// autogeneratednocheckin

extern "C"
{
extern void Add_Auto_Cmds_mapserver(void);
extern void _mapserver_AutoRun_SPECIALINTERNAL(void);
extern void autoStruct_fixup_ArchitectMapComponent(void);
extern void autoStruct_fixup_ArchitectMapComponentPlace(void);
extern void autoStruct_fixup_ArchitectMapHeader(void);
extern void autoStruct_fixup_ArchitectMapSubMap(void);
extern void autoStruct_fixup_MMElement(void);
extern void autoStruct_fixup_MMElementList(void);
extern void autoStruct_fixup_MMRegion(void);
extern void autoStruct_fixup_MMRegionButton(void);
extern void autoStruct_fixup_MMScrollSet_Loader(void);
extern void autoStruct_fixup_MapLimit(void);
extern void autoStruct_fixup_MissionHeaderDescription(void);
extern void autoStruct_fixup_MissionSearchGuestBio(void);
extern void autoStruct_fixup_MissionSearchHeader(void);
extern void autoStruct_fixup_MissionSearchParams(void);


void doAutoRuns_mapserver_0(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	_mapserver_AutoRun_SPECIALINTERNAL();
}



void doAutoRuns_mapserver_1(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
	Add_Auto_Cmds_mapserver();
	autoStruct_fixup_ArchitectMapComponent();
	autoStruct_fixup_ArchitectMapComponentPlace();
	autoStruct_fixup_ArchitectMapHeader();
	autoStruct_fixup_ArchitectMapSubMap();
	autoStruct_fixup_MMElement();
	autoStruct_fixup_MMElementList();
	autoStruct_fixup_MMRegion();
	autoStruct_fixup_MMRegionButton();
	autoStruct_fixup_MMScrollSet_Loader();
	autoStruct_fixup_MapLimit();
	autoStruct_fixup_MissionHeaderDescription();
	autoStruct_fixup_MissionSearchGuestBio();
	autoStruct_fixup_MissionSearchHeader();
	autoStruct_fixup_MissionSearchParams();
}



void doAutoRuns_mapserver_2(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
}



void doAutoRuns_mapserver_3(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
}



void doAutoRuns_mapserver_4(void)
{
	static int once = 0;
	if (once) return;
	once = 1;
}

extern void utilitiesLibPreAutoRunStuff(void);
int MagicAutoRunFunc_mapserver(void)
{
	utilitiesLibPreAutoRunStuff();
	doAutoRuns_mapserver_0();
	doAutoRuns_mapserver_1();
	doAutoRuns_mapserver_2();
	doAutoRuns_mapserver_3();
	doAutoRuns_mapserver_4();
	return 0;
}

void do_auto_runs(void)
{
	MagicAutoRunFunc_mapserver();
}

};


#if 0
PARSABLE
16
"Add_Auto_Cmds_mapserver" "autogen_magiccommands" 1 "" "" 
"_mapserver_AutoRun_SPECIALINTERNAL" "_SPECIAL_INTERNAL" 0 "" "" 
"autoStruct_fixup_ArchitectMapComponent" "D:\CoH\repotest\Source\MapServer\..\Common\group\groupMetaMinimap.h" 1 "" "" 
"autoStruct_fixup_ArchitectMapComponentPlace" "D:\CoH\repotest\Source\MapServer\..\Common\group\groupMetaMinimap.h" 1 "" "" 
"autoStruct_fixup_ArchitectMapHeader" "D:\CoH\repotest\Source\MapServer\..\Common\group\groupMetaMinimap.h" 1 "" "" 
"autoStruct_fixup_ArchitectMapSubMap" "D:\CoH\repotest\Source\MapServer\..\Common\group\groupMetaMinimap.h" 1 "" "" 
"autoStruct_fixup_MMElement" "D:\CoH\repotest\Source\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMElementList" "D:\CoH\repotest\Source\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMRegion" "D:\CoH\repotest\Source\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMRegionButton" "D:\CoH\repotest\Source\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MMScrollSet_Loader" "D:\CoH\repotest\Source\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MapLimit" "D:\CoH\repotest\Source\MapServer\..\Common\storyarc\playerCreatedStoryarcValidate.h" 1 "" "" 
"autoStruct_fixup_MissionHeaderDescription" "D:\CoH\repotest\Source\MapServer\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchGuestBio" "D:\CoH\repotest\Source\MapServer\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchHeader" "D:\CoH\repotest\Source\MapServer\..\Common\MissionSearch.h" 1 "" "" 
"autoStruct_fixup_MissionSearchParams" "D:\CoH\repotest\Source\MapServer\..\Common\MissionSearch.h" 1 "" "" 
#endif
