#include "pch.h"
#include "sourceparser.h"
#include <cstdio>
#include "strutils.h"

namespace fs = std::filesystem;

int gVerbose = 0;

typedef struct
{
    char optionName[128];
    int *pOption;
} OPTION_STRUCT;

OPTION_STRUCT gOptions[] = 
{
    {
        "Verbose",
        &gVerbose
    }
};

#define NUM_OPTIONS (sizeof(gOptions) / sizeof(gOptions[0]))

static char* RemoveTerminatingSeparator(char* dir)
{
    auto length = strlen(dir);
    if (length > 0 && (dir[length - 1] == '\\' || dir[length - 1] == '/'))
    {
        dir[length - 1] = 0;
    }
    return dir;
}

int ReadOptionsFromFile(Tokenizer *pTokenizer)
{
    Token token;
    enumTokenType eType;

    int iNumFound = 0;

    while ((eType = pTokenizer->GetNextToken(&token)) != TOKEN_NONE)
    {
        if (eType == TOKEN_IDENTIFIER)
        {
            int i;

            for (i=0; i < NUM_OPTIONS; i++)
            {
                if (strcmp(gOptions[i].optionName, token.sVal) == 0)
                {
                    pTokenizer->AssertNextTokenTypeAndGet(&token, TOKEN_RESERVEDWORD, RW_EQUALS, "Expected = after option name");
                    pTokenizer->AssertNextTokenTypeAndGet(&token, TOKEN_INT, 0, "Expected int after =");
                    *(gOptions[i].pOption) = token.iVal;

                    iNumFound++;
                }
            }
        }
    }

    return iNumFound;
}

void WriteOptionsFile(char *pFileName)
{
    int i;

    FILE *pOutFile = fopen_nofail(pFileName, "wt");

    fprintf(pOutFile, "//This file contains options for StructParser. It is autogenerated as new options occur.\n//The syntax is pretty self-explanatory\n//autogenerated" "nocheckin\n\n");

    for (i = 0; i < NUM_OPTIONS; i++)
    {
        fprintf(pOutFile, "%s = %d\n\n", gOptions[i].optionName, *(gOptions[i].pOption));
    }

    fclose(pOutFile);
}

void ProcessOptionFile(void)
{
    char exeName[MAX_PATH];
    char optionFileName[MAX_PATH];
    int iNumOptionsFound = 0;

    Tokenizer tokenizer;
    
    GetModuleFileNameA(NULL, exeName, MAX_PATH);

    TruncateStringAtLastOccurrence(exeName, '\\');

    sprintf(optionFileName, "%s\\%s", exeName, "structparser_settings.txt");

    if (tokenizer.LoadFromFile(optionFileName))
    {
        iNumOptionsFound = ReadOptionsFromFile(&tokenizer);
    }

    if (iNumOptionsFound != NUM_OPTIONS)
    {
        WriteOptionsFile(optionFileName);
    }
}

int main(int argc, char* argv[])
{
    ProcessOptionFile();

    char commandLine[2000];
    commandLine[0] = 0;

    for (int i=0; i < argc; ++i)
    {
        sprintf(commandLine + strlen(commandLine), " %s", argv[i]);
    }

    char *pSubStrings[20];
    int iStringsFound = SubDivideStringAndRemoveWhiteSpace(pSubStrings, commandLine, 'X', 20);

    if (iStringsFound != 7)
    {
        printf("ERROR: Couldn't find required arguments for StructParser. Should be X $(ProjectPath) X $(ProjectDir)..\\..\\src\\ X $(ProjectDir)..\\..\\..\\..\\Common\\ X $(Platform) X $(Configuration) X $(SolutionPath)");

        for (int i = 0; i < iStringsFound; i++)
        {
            printf("%d: %s\n", i, pSubStrings[i]);
        }
    
        fflush(stdout);
        Sleep(100);
        return 1;
    }

    for (int i = 0; i < iStringsFound; ++i)
    {
        printf("%s", pSubStrings[i]);

        if (i < iStringsFound - 1)
        {
            printf(" X ");
        }
    }
    printf("\n");

    // Full path of project file, project file must at least exist in the specified location
    fs::path projectPath{ fs::absolute(pSubStrings[1]) };
    if (!fs::exists(projectPath))
    {
        printf("ERROR: Argument 1 (project path) is not valid");
        return 1;
    }
    // Root of all source files in the project, must exist
    fs::path sourceDir{ fs::absolute(RemoveTerminatingSeparator(pSubStrings[2])) };
    if (!fs::exists(sourceDir))
    {
        printf("ERROR: Argument 2 (source dir) is not valid");
        return 1;
    }
    // Root of all common source files in the code base, must exist
    fs::path commonDir{ fs::absolute(RemoveTerminatingSeparator(pSubStrings[3])) };
    if (!fs::exists(commonDir))
    {
        printf("ERROR: Argument 3 (common dir) is not valid");
        return 1;
    }
    // Platform, we can only hope it is valid, at least we know it mist be longer than zero chars
    std::string platform{ pSubStrings[4] };
    if (platform.empty())
    {
        printf("ERROR: Argument 4 (platform) is not valid");
        return 1;
    }
    // Configuration, we can only hope it is valid, at least we know it mist be longer than zero chars
    std::string configuration{ pSubStrings[5] };
    if (configuration.empty())
    {
        printf("ERROR: Argument 5 (configuration) is not valid");
        return 1;
    }
    // Root of all common source files in the code base, must exist
    fs::path solutionPath{ fs::absolute(pSubStrings[6]) };
    if (!fs::exists(solutionPath))
    {
        printf("ERROR: Argument 6 (solution path) is not valid");
        return 1;
    }

    auto sourceParser = std::make_unique<SourceParser>(); // SourceParser is over a MB big so don't allocate it on the stack
    return sourceParser->ParseSource(projectPath, sourceDir, commonDir, platform, configuration, solutionPath);
}